### ISSUE TITLE
Resource provision with resource that doens't match provisioner leaves resource in state file

### ISSUE THREAD

**Issue by astromechza** [astromechza/score-flyio#9]
If you try:

```
resources:
  db:
    type: postgre   # missing s on the end
```

It will fail with a missing provisioner as expected, however it will also leave the resource lying around in the state file!

```
resources:
  postgre.default#demo-app.db2:
    guid: 3e07f4b7-72a7-4db7-537b-402c89aed49d
    type: postgre
    class: default
    id: demo-app.db2
    metadata: {}
    params: {}
    source_workload: ""
    provisioner: ""
    state: {}
```

This then fails to be deprovisioned because no provisioner can be found. I should fix this.
